In [1]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [7]:
#Standardisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#to calculate mean and variance
independent = sc.fit_transform(independent)
independent = sc.transform(independent)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [8]:
#GridSearch
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'friedman_mse', 'poisson' ], 'max_features':['auto', 'sqrt', 'log2'], 'splitter':['best', 'random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.60788349 0.62883332 0.64563386 0.63804318
        nan        nan 0.72209966 0.6600976  0.67515323 0.67089132
        nan        nan 0.66622048 0.64811844 0.69653412 0.63060823]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [9]:
#print best parameter after tuning
#print(grid.best_params_)
result = grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}:

In [10]:
table = pd.DataFrame.from_dict(result)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004596,0.005629,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.000575,0.001150,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.008691,0.005036,0.005917,0.002059,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.763376,0.573989,0.747082,0.456373,0.498597,0.607883,0.126176,12
3,0.003748,0.004394,0.004160,0.005095,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.691221,0.578515,0.604721,0.698906,0.570803,0.628833,0.055287,11
4,0.005603,0.005793,0.004039,0.005841,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.695099,0.609541,0.675533,0.515889,0.732107,0.645634,0.076099,8
5,0.010413,0.008791,0.003128,0.006255,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.684516,0.511476,0.703828,0.667759,0.622637,0.638043,0.068742,9
6,0.001156,0.002312,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.000762,0.000397,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.007149,0.005245,0.002444,0.003356,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.746951,0.686369,0.701339,0.739392,0.736447,0.722100,0.023791,1
9,0.007759,0.003276,0.000000,0.000000,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.646372,0.641318,0.670399,0.580159,0.762240,0.660098,0.059111,6
10,0.006805,0.005702,0.004078,0.006573,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.643887,0.574668,0.739557,0.684397,0.733258,0.675153,0.061130,3
11,0.004303,0.005386,0.006255,0.007661,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.673122,0.628259,0.698657,0.636601,0.717819,0.670891,0.034558,4
12,0.000687,0.001375,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.002502,0.005004,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.011090,0.004483,0.001302,0.002058,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.648751,0.622405,0.681272,0.712252,0.666422,0.666220,0.030234,5
15,0.004043,0.003962,0.004683,0.006219,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.676263,0.508901,0.741510,0.610043,0.703875,0.648118,0.081798,7
16,0.005006,0.004158,0.003218,0.006149,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.774275,0.631490,0.719480,0.669138,0.688287,0.696534,0.048207,2
17,0.010912,0.006689,0.003351,0.003967,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.667280,0.506824,0.639293,0.648357,0.691287,0.630608,0.064405,10

In [12]:
age_input = int(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = int(input("Children: "))
sex_male_input = int(input("Sex Male 0 or 1: "))
smoker_yes_input = int(input("Smoker yes 0 or 1: "))

Age: 19
BMI: 27.9
Children: 0
Sex Male 0 or 1: 0
Smoker yes 0 or 1: 1

In [13]:
new_data = [[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]]

In [14]:
new_data_standardized = sc.transform(new_data)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [15]:
Future_Prediction = grid.predict(new_data_standardized)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[48970.2476]