In [1]:
#importing the libraries
import numpy as np #for array and matrices
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [7]:
#GridSearch
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error', 'friedman_mse', 'poisson' ], 'max_features':['auto', 'sqrt', 'log2'], 'splitter':['best', 'random']}

grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3, n_jobs = -1) 
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
27 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\User\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\User\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.67092765 0.66100607 0.70711025 0.61147395
        nan        nan 0.69444495 0.67533135 0.71258442 0.58580693
        nan        nan 0.65933087 0.62251748 0.6459387  0.67625465]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [8]:
#print best parameter after tuning
#print(grid.best_params_)
result = grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}:

In [9]:
table = pd.DataFrame.from_dict(result)

In [10]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003252,0.005239,0.000000,0.000000,squared_error,auto,best,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
1,0.002082,0.003864,0.000000,0.000000,squared_error,auto,random,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
2,0.009120,0.005095,0.000000,0.000000,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.717463,0.610983,0.672768,0.733272,0.620152,0.670928,0.049452,6
3,0.009377,0.007656,0.006248,0.007652,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.727790,0.595941,0.660225,0.714181,0.606894,0.661006,0.053759,7
4,0.012500,0.006250,0.003125,0.006250,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.741518,0.658299,0.749663,0.698921,0.687149,0.707110,0.034184,2
5,0.005062,0.005707,0.007217,0.007086,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.541398,0.489081,0.656769,0.732982,0.637139,0.611474,0.086447,11
6,0.001537,0.001891,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
7,0.000827,0.001654,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
8,0.008764,0.005965,0.000000,0.000000,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.690838,0.494102,0.799878,0.760810,0.726596,0.694445,0.106494,3
9,0.013061,0.005538,0.001128,0.002257,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.710122,0.615425,0.644223,0.698188,0.708698,0.675331,0.038478,5
10,0.011561,0.007067,0.000000,0.000000,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.788429,0.610352,0.680812,0.740054,0.743275,0.712584,0.061498,1
11,0.006434,0.007885,0.003031,0.003908,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.541291,0.525198,0.618994,0.619405,0.624146,0.585807,0.043255,12
12,0.000000,0.000000,0.000000,0.000000,poisson,auto,best,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000000,0.000000,0.000000,0.000000,poisson,auto,random,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
14,0.006253,0.007658,0.009375,0.007654,poisson,sqrt,best,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.735272,0.629694,0.706448,0.527892,0.697348,0.659331,0.074279,8
15,0.003125,0.006250,0.009374,0.007654,poisson,sqrt,random,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.666068,0.593229,0.589111,0.697929,0.566249,0.622517,0.050445,10
16,0.006249,0.007654,0.009375,0.007655,poisson,log2,best,"{'criterion': 'poisson', 'max_features': 'log2...",0.570188,0.484560,0.726487,0.681612,0.766847,0.645939,0.104077,9
17,0.009375,0.007654,0.006250,0.007654,poisson,log2,random,"{'criterion': 'poisson', 'max_features': 'log2...",0.694988,0.585073,0.703342,0.684493,0.713377,0.676255,0.046572,4

In [11]:
age_input = int(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = int(input("Children: "))
sex_male_input = int(input("Sex Male 0 or 1: "))
smoker_yes_input = int(input("Smoker yes 0 or 1: "))

Age: 23
BMI: 20.7
Children: 0
Sex Male 0 or 1: 1
Smoker yes 0 or 1: 0

In [12]:
Future_Prediction = grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[2302.3]

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(