In [1]:
#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#Reading the Dataset
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset, drop_first = True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [6]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [7]:
#Standardisation
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
#to calculate mean and variance
independent = sc.fit_transform(independent)
independent = sc.transform(independent)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [8]:
#GridSearch
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LinearRegression
param_grid = {'fit_intercept':[True, False], 'copy_X':[True, False], 'n_jobs':[1, 5], 'positive':[True, False]}

grid = GridSearchCV(LinearRegression(), param_grid, refit = True, verbose = 3, n_jobs = -1)
#fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False], 'n_jobs': [1, 5],
                         'positive': [True, False]},
             verbose=3)

In [9]:
#print best parameter after tuning
#print(grid.best_params_)
result = grid.cv_results_

print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': True}:

In [10]:
table = pd.DataFrame.from_dict(result)

In [11]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005971,0.005795,0.008760,0.006359,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
1,0.003851,0.003865,0.003012,0.003812,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,5
2,0.011527,0.002388,0.004153,0.003356,True,True,5,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
3,0.004094,0.002557,0.000824,0.001226,True,True,5,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,5
4,0.003468,0.005103,0.003196,0.005248,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.776745,-1.194084,-0.887780,-0.885240,-0.815373,-0.911845,0.147312,13
5,0.002802,0.003272,0.000521,0.001043,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.604490,0.564390,0.619146,0.586492,0.630131,0.600930,0.023413,9
6,0.012707,0.003923,0.002260,0.002679,True,False,5,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",-0.776745,-1.194084,-0.887780,-0.885240,-0.815373,-0.911845,0.147312,13
7,0.000214,0.000429,0.002181,0.002855,True,False,5,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.604490,0.564390,0.619146,0.586492,0.630131,0.600930,0.023413,9
8,0.003946,0.003478,0.000000,0.000000,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
9,0.001237,0.001538,0.003965,0.004021,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,5
10,0.010280,0.003475,0.001215,0.001787,False,True,5,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
11,0.000830,0.001077,0.002717,0.002636,False,True,5,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,5
12,0.005691,0.004682,0.000750,0.000948,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.776745,-1.194084,-0.887780,-0.885240,-0.815373,-0.911845,0.147312,13
13,0.003381,0.003022,0.000205,0.000410,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.604490,0.564390,0.619146,0.586492,0.630131,0.600930,0.023413,9
14,0.006575,0.003665,0.002942,0.004942,False,False,5,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",-0.776745,-1.194084,-0.887780,-0.885240,-0.815373,-0.911845,0.147312,13
15,0.003517,0.004762,0.003545,0.004726,False,False,5,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.604490,0.564390,0.619146,0.586492,0.630131,0.600930,0.023413,9

In [12]:
age_input = int(input("Age: "))
bmi_input = float(input("BMI: "))
children_input = int(input("Children: "))
sex_male_input = int(input("Sex Male 0 or 1: "))
smoker_yes_input = int(input("Smoker yes 0 or 1: "))

Age: 19
BMI: 27.9
Children: 0
Sex Male 0 or 1: 0
Smoker yes 0 or 1: 1

In [13]:
new_data = [[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]]

In [14]:
new_data_standardized = sc.transform(new_data)

C:\Users\User\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [15]:
Future_Prediction = grid.predict(new_data_standardized)
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[[146425.49664166]]